WebApplication1/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.IO;

namespace WebApplication1.Models
{
    public class Patient
    {
        public int ID { get; set; }

        [Display(Name = "Imię")]
        [StringLength(20, MinimumLength = 3)]
        public string Name { get; set; }

        [Display(Name = "Nazwisko")]
        [StringLength(20, MinimumLength = 3)]
        public string LastName { get; set; }

        [PESEL]
        [Required]
        [Index(IsUnique = true)]
        [StringLength(11)]
        [Display(Name = "Pesel")]
        public string PESEL { get; set; }

        [Display(Name = "Badania")]
        public virtual List<Exam> Exams { get; set; }
    }

    public class PatientCreateViewModel
    {
        [Display(Name = "Imię")]
        [StringLength(20, MinimumLength = 3,ErrorMessage = "Podaj imie pacjenta")]
        public string Name { get; set; }

        
        [Display(Name = "Nazwisko")]
        [StringLength(20, MinimumLength = 3,ErrorMessage = "Podaj nazwisko pacjenta")]
        public string LastName { get; set; }

        [PESEL]
        [StringLength(11,MinimumLength = 11,ErrorMessage = "Niepoprawny number pesel")]
        [Display(Name = "Pesel")]
        public string PESEL { get; set; }

        public bool AlreadyExists { get; set; } = false;
        public Patient ActualPatient { get; set; }
    }

    public class PatientEditViewModel
    {
        public int ID { get; set; }

        [Display(Name = "Imię")]
        [StringLength(20, MinimumLength = 3)]
        public string Name { get; set; }

        [Display(Name = "Nazwisko")]
        [StringLength(20, MinimumLength = 3)]
        public string LastName { get; set; }
    }

    public class PESELAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (!(value is string))
            {
                throw new InvalidDataException("PESEL MUST be a string, check your code");
            }
            var data = (string) value;
            data = data.Trim();

            if (data.Length != 11)
            {
                return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));
            }

            int checksum = 0;
            // the algorithm to check if the pesel is valid
            checksum += data[0]*1;
            checksum += data[1]*3;
            checksum += data[2]*7;
            checksum += data[3]*9;
            checksum += data[4]*1;
            checksum += data[5]*3;
            checksum += data[6]*7;
            checksum += data[7]*9;
            checksum += data[8]*1;
            checksum += data[9]*3;
            checksum += data[10]*1;

            if (checksum%10 == 0)
            {
                return null;
            }
            return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));
        }
    }
}

WebApplication1/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "mod,admin")]
    public class ExamController : Controller
    {
        private readonly LabContext db;

        public ExamController()
        {
            this.db = new LabContext();
        }

        public ExamController(LabContext context)
        {
            this.db = context;
        }

        // GET: Badania
        public ActionResult Index()
        {
            return View(db.Badania.ToList());
        }

        // GET: Badania/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam badanie = db.Badania.Include(b => b.Patient).FirstOrDefault(p => p.Id == id);
            if (badanie == null)
            {
                return HttpNotFound();
            }
            return View(badanie);
        }

        // GET: Badania/Create
        public ActionResult Create(int? UserId)
        {
            if (UserId != null)
            {
                var pesel = db.Pacjenci.FirstOrDefault(p => p.ID == UserId.Value)?.PESEL;
                if (pesel != null)
                {
                    return View(new ExamCreateViewModel() {PESEL = pesel});
                }
            }
            return View();
        }

        // POST: Badania/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamCreateViewModel badanie)
        {
            if (ModelState.IsValid)
            {
                var patient = db.Pacjenci.FirstOrDefault(p => p.PESEL == badanie.PESEL);
                if (patient == null)
                {
                    badanie.IsExistingPesel = false;
                    return View(badanie);
                }
                var exam = new Exam()
                {
                    Name = badanie.Name,
                    Patient = patient,
                    Result = new ExamResult() {Complete = false},
                    Issued = DateTime.Now
                };
                db.Badania.Add(exam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(badanie);
        }

        // GET: Badania/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam badanie = db.Badania.Find(id);
            if (badanie == null)
            {
                return HttpNotFound();
            }
            return View(badanie);
        }

        // POST: Badania/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Details")] Exam badanie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(badanie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(badanie);
        }

        public PartialViewResult ForUser(int id)
        {
            var patient = db.Pacjenci.Find(id);
            if (patient != null)
            {
                return PartialView(patient);
            }
            return PartialView("_ErrorPartial");
        }
        // GET: Badania/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam badanie = db.Badania.Find(id);
            if (badanie == null)
            {
                return HttpNotFound();
            }
            return View(badanie);
        }

        // POST: Badania/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exam badanie = db.Badania.Find(id);
            db.Badania.Remove(badanie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles="admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddResult(ExamResultAddViewModel wyniki)
        {
            if (ModelState.IsValid)
            {
                var exam = db.Badania.FirstOrDefault(b => b.Id == wyniki.ExamId);
                if (exam == null)
                {
                    return new HttpNotFoundResult("Brak badania z takim ID");
                }
                exam.Result = new ExamResult()
                {
                    Complete = wyniki.Complete,
                    Details = wyniki.Details,
                    ReadyTime = DateTime.Now
                };
                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wyniki);
        }

        public ActionResult AddResult(int? ExamId)
        {
            if (ExamId.HasValue)
            {
                var exam = db.Badania.FirstOrDefault(b => b.Id == ExamId.Value);
                if (exam == null)
                {
                    return new HttpNotFoundResult("Brak badania z takim ID");
                }
                var data = new ExamResultAddViewModel()
                {
                    Complete = exam.Result.Complete,
                    ExamId = exam.Id,
                    Details = exam.Result.Details
                };
                return View(data);
            }
            else
            {
                return new HttpNotFoundResult();
            }
        }
    }
}

WebApplication1/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Routing.Constraints;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "mod,admin")]
    public class PatientController : Controller
    {
        private readonly LabContext db;

        public PatientController(LabContext db)
        {
            this.db = db;
        }

        public PatientController()
        {
            this.db = new LabContext();
        }

        // GET: Patient
        public ActionResult Index()
        {
            return View(db.Pacjenci.ToList());
        }

        // GET: Patient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient pacjent =
                db.Pacjenci.Include(p => p.Exams).First(p => p.ID == id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }


        // GET: Patient/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientCreateViewModel patientData)
        {
            if (ModelState.IsValid)
            {
                var dbPatient = db.Pacjenci.FirstOrDefault(p => p.PESEL == patientData.PESEL.Trim());
                if (dbPatient != null)
                {
                    patientData.AlreadyExists = true;
                    patientData.ActualPatient = dbPatient;
                    return View(patientData);
                }
                var newPatient = new Patient()
                {
                    LastName = patientData.LastName,
                    Name = patientData.Name,
                    PESEL = patientData.PESEL
                };
                db.Pacjenci.Add(newPatient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patientData);
        }

        // GET: Patient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient pacjent = db.Pacjenci.Find(id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            var data = new PatientEditViewModel()
            {
                ID = pacjent.ID,
                LastName = pacjent.LastName,
                Name = pacjent.Name
            };
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PatientEditViewModel pacjent)
        {
            if (ModelState.IsValid)
            {
                var newData = new Patient()
                {
                    ID = pacjent.ID,
                    LastName = pacjent.LastName,
                    Name = pacjent.Name
                };
                db.Entry(newData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pacjent);
        }

        // GET: Patient/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient pacjent = db.Pacjenci.Find(id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }

        // POST: Patient/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient pacjent = db.Pacjenci.Find(id);
            db.Pacjenci.Remove(pacjent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Patient/Create.cshtml
@model WebApplication1.Models.PatientCreateViewModel

@{
    ViewBag.Title = "Dodaj pacjenta";
}

<h2>Dodaj Pacjenta</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PESEL, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PESEL, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PESEL, "", new {@class = "text-danger"})
            </div>
        </div>
        @if (Model != null && Model.AlreadyExists)
        {
            <div class="form-group">
                <div class="col-md-10">
                    @Html.Label("Podany PESEL juz istnieje", "Podany PESEL juz istnieje",
                        new {@class = "text-danger field-validation-error"})
                    @Html.ActionLink("Przejdz do pacjenta", "Details", "Patient",
                        new {ID = Model.ActualPatient.ID}, new {@class = "btn btn-primary"})
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Patient/Delete.cshtml
@model WebApplication1.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pacjent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PESEL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PESEL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Patient/Details.cshtml
@using WebApplication1.HtmlHelper
@using WebApplication1.Models
@model Patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pacjent</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PESEL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PESEL)
        </dd>
    </dl>
    <h3>
        @Html.DisplayNameFor(model => model.Exams)
    </h3>
    @if (User.IsInRole("admin"))
    {
        @Html.ActionLink("Dodaj badanie", "Create", "Exam", new {UserId = Model.ID}, new {@class = "btn btn-success"})
    }

    @Html.Action("ForUser", "Exam", new {id = Model.ID})
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.ID}) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Patient/Edit.cshtml
@model WebApplication1.Models.PatientEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pacjent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Patient/Index.cshtml
@model IEnumerable<WebApplication1.Models.Patient>

@{
    ViewBag.Title = "Pacjenci";
}

<h2>Pacjenci</h2>

<p>
    @Html.ActionLink("Dodaj pacjenta", "Create")
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PESEL)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr class="row-link clickable-row" data-href="@Url.Action("Details", new {id = item.ID})">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PESEL)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new {id = item.ID}, new {@class = "btn btn-default"})
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Delete", "Delete", new {id = item.ID}, new {@class = "btn btn-danger"})
                }
            </td>
        </tr>
    }
    </tbody>
</table>